process.env.PROXY_INTEGRATION = 'false'
process.env.TRACE_URL = 'http://tn-driver-profile.stg.k8s.mypna.com'
process.env.MATCHING_URL = 'http://osrm-api-ranking-unidb-na.stg.k8s.mypna.com'
process.env.TRACKING_URL = 'http://sync4routing-na.stg.k8s.mypna.com'
process.env.ROUTING_URL = 'http://sync4routing-na.stg.k8s.mypna.com'