version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CommuteRouteSam"
s3_bucket = "commute-route-bucket"
s3_prefix = "SAM"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "StageParam=\"prod\""
